version: '3.8'
services:
  # Servicio de PostgreSQL
  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: agenda_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: universidad
    ports:
      - "5432:5432"